name: Linting and Testing with Github Actions
on: [pull_request]
jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
                python-version: 3.12
          - uses: actions/cache@v4
            with:
                path: ~/.cache/pip
                key: ${{runner.os}}-pip-${{hashFiles('**/requirements.txt')}}
          - run: |
                pip install -r ./assets/requirements.txt
          - name: Run Linter
            run: |
                flake8 ./assets/
          - name: Run Tests
            run: pytest